### PR TITLE
Windows compat fixes

### PR DESCRIPTION
**Pull request by Xylakant**
The current version of warbler-exec does not run on windows due to two main issues:
- Variable substitution happens with %var% and not with $var
- The path separator is ";" not ":"

Then there's a minor issue with jruby < 1.7.1 and chdir: The spawned subshell on windows will not inherit the parents path, so the use of chdir in the script has no effect. The directory change must happen in the subshell.

### CODE REVIEW

**Comment by jkutner** [comment]
Thanks for fixing this!

**Comment by Xylakant** [comment]
could you roll that in a minor release and push it to rubygems? That makes installation much easier :)

**Comment by jkutner** [comment]
Yes. I'll get that out shortly!

**Comment by jkutner** [comment]
This in in 0.1.1

**Pull request merged**
